### ISSUE TITLE
Errors when used with ember-cli-htmlbars@4 _without_ ember-cli-htmlbars-inline-precompile

### ISSUE THREAD

**Issue by rwjblue** [xg-wang/ember-async-to-generator#174]
Specifically, this code:

https://github.com/xg-wang/ember-async-to-generator/blob/b3f89becffac9850b2d5728ba02fd5577a3250cc/index.js#L47-L49

Fails when used with ember-cli-htmlbars, because `p` (the item in the `app.options.babel.plugins` array) is formatted like:

```js
{ _parallelBabel:
   { requireFile:
      '/Users/rjackson/src/linkedin/ember-cli-pemberly-i18n/node_modules/ember-cli-htmlbars/lib/require-from-worker.js',
     buildUsing: 'build',
     params:
      { templateCompilerPath:
         '/Users/rjackson/src/linkedin/ember-cli-pemberly-i18n/node_modules/ember-source/dist/ember-template-compiler.js',
        parallelConfigs: [Array],
        modules: [Object] } },
  baseDir: [Function: baseDir],
  cacheKey: [Function: cacheKey] }
```

At the moment, we get:

`Cannot read property 'match' of undefined`

**Comment by xg-wang** [comment]
This project switched to use `ember-cli-babel-plugin-helpers` in v2.0.0, should be fixed now.
