### ISSUE TITLE
Usage of `_findApp` means addon code itself is not transformed properly

### ISSUE THREAD

**Issue by rwjblue** [xg-wang/ember-async-to-generator#175]
Adding `ember-async-to-generator` as a dependency of an addon _should_ result in that addon's code being transformed with `@babel/plugin-transform-async-to-generator`.

Instead of using `this._findApp` we should be using `this.parent.options.babel.plugins` (to directly modify our parent, not the host app).

**Comment by xg-wang** [comment]
Fixed in v2.0.0
